env:
  TERM: xterm-256color

window:
  padding:
    x: 2
    y: 2

  dynamic_title: true

font:
  normal:
    family: JetBrainsMono Nerd Font

  size: 10

import:
  - ~/.config/alacritty/catppuccin-mocha.yml
