import:
  - ~/.config/alacritty/catppuccin-mocha.yml

env:
  TERM: xterm-256color

window:
  padding:
    y: 20
    x: 25

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Bold

  size: 10
